### ISSUE TITLE
No data on /stereo/points2

### ISSUE THREAD

**Issue by void-robotics** [i3drobotics/deimos-ros#3]
Thanks for creating this ROS driver; it's working fairly well.

I'm getting data from other topics (like /stereo/right/image_raw), but no data is coming from /stereo/points2.

How do I get data from this? Also my goal is to poll any point in the image for a depth; so if there's an easier/other way to do this, I could also do that.

Thanks,
Nathan

**Comment by jveitchmichaelis** [comment]
Have you calibrated the camera? Tara comes with an onboard calibration, but it's always worth trying again. The Deimos package expects that you've performed your own calibration rather than using the onboard one. There are some details in the readme, or you can look at: http://wiki.ros.org/camera_calibration/Tutorials/StereoCalibration. You should also see the rectified image topics if the camera is calibrated (e.g. /stereo/left/image_rect)

If you want to poll a specific location, you're better off processing the disparity map directly and using OpenCV to reproject those specific points to 3D. You'll also need the camera calibration for that.

There are other tools in ROS e.g. http://wiki.ros.org/stereo_image_proc which can display the disparity map to see if things look sensible.

**Comment by void-robotics** [comment]
Ok; so /stereo/points2 is empty by default.

If I want to poll a specific location, would the best approach be to use OpenCV's [reprojectImageTo3D](https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#void%20reprojectImageTo3D%28InputArray%20disparity,%20OutputArray%20_3dImage,%20InputArray%20Q,%20bool%20handleMissingValues,%20int%20ddepth%29)?

Why would I need to reproject if [stereo_image_proc](http://wiki.ros.org/stereo_image_proc) outputs points2, which I believe is xyz values for every point in the image?

**Comment by jveitchmichaelis** [comment]
If it's still empty, check that the calibration is good/exists, that's likely to be the problem.

Looks like it is indeed [structured](https://github.com/ros-perception/image_pipeline/blob/indigo/stereo_image_proc/src/nodelets/point_cloud2.cpp#L173). This often isn't the case when working with 3D data for formats like e.g. PLY which is usually just a list of XYZRGB points. In this case, you might find that performing 2D operations on a disparity map is easier than on a point cloud. And yes, `reprojectImageTo3D` should work.

However, on your last point, you almost certainly won't get a 3D location for every point in the image due to occlusions and overlap between the cameras. This means you'll get some parts of the image with no calculated disparity values - these points are not reprojected as there would be no physical meaning in assigning them a 3D location. In ROS these points [are set to NaNs](https://github.com/ros-perception/image_pipeline/blob/8d01c930e66bdeb58c4b138539a64ddea0b17e10/stereo_image_proc/src/nodelets/point_cloud2.cpp#L205).

**Comment by void-robotics** [comment]
Somehow the points2 data just appeared; so that problem is solved.

Although getting a 3D location for every point is impossible, I'm still confused how `reprojectImageTo3D` is preferred over [polling](https://answers.ros.org/question/191265/pointcloud2-access-data/) from the point cloud?

**Comment by jveitchmichaelis** [comment]
It's not better in this case - use the point cloud.
