### ISSUE TITLE
uncalibrated error

### ISSUE THREAD

**Issue by void-robotics** [i3drobotics/deimos-ros#7]
Hello,

I get the following error:

```
[N=/stereo/stereo_image_proc-120]: Rectified topic '/stereo/left/image_rect' requested but camera publishing '/stereo/left/camera_info' is uncalibrated
```

Although I did `mkdir ~/.ros/camera_info -p ` and then a clean build, there is now nothing in that folder; but I had this working a month ago. What might be the issue?

I don't remember manually creating the yaml files, but is that step necessary?

**Comment by jveitchmichaelis** [comment]
Sorry for the delay (hopefully you figured this out in  the meantime). The yaml files are generated when you calibrate the camera in ROS. Worth double checking that the path to the camera info is correct in the launch file and that they're named correctly.

`file://${ROS_HOME}/camera_info/right.yaml` etc

If you had it working before, I'm guessing you calibrated the cameras first. The file isn't generated automatically when you launch the node, it's a separate thing.

**Comment by void-robotics** [comment]
I think I just recreated the yaml; thanks

**Comment by mbudris** [comment]
Is it possible to use the calibration yaml files provided by tara on purchase? I renamed the files to left.yaml and right.yam, but deimos complains it is not calibrated.

**Comment by jveitchmichaelis** [comment]
@mbudris at the moment not directly, but you could copy the relevant parameters from the Tara yaml file and it should work.

It may be quicker to just calibrate using ROS though. It's good practice to learn how to do this, because any adjustment to the cameras e.g. mechanical, taking them out of the case, mounting it to something can ruin the factory calibration.
