### ISSUE TITLE
Topic (/stereo/image_raw) rendering issue

### ISSUE THREAD

**Issue by farhanmubasher** [i3drobotics/deimos-ros#8]
**Hi,**
First of all thanks for everything,
I've successfully run the package, every topic is giving fine results except  /stereo/image_raw, when i run this topic the video streaming looks like everything is shaking or everything in video has its projection.

I have shared two images for better understanding:

**This is the result image of topic /stereo/concat:**
![image](https://user-images.githubusercontent.com/22928889/50518991-a5946b00-0ab0-11e9-85f5-4a98cb2ad2d7.png)

**This is the result image of topic /stereo/image_raw:**
![image2](https://user-images.githubusercontent.com/22928889/50519046-dd9bae00-0ab0-11e9-9ae2-20c33baabe11.png)

I don't know why it looks like blurry or shaking, can you please help me with this.
**I'm using Tara stereo cam on Jetson Tx2 board.**
Thanks in advance.

**Comment by jveitchmichaelis** [comment]
The raw image looks that way because the Tara board captures the stereo pair in a single image (i.e. it concatenates the outputs from both sensors). The left and right views are placed into two of the colour channels (I think red and green). It's not blurred, you're simply seeing both images overlaid.

You can see this if you try opening the camera as a normal webcam.

If you need to use a raw image, use `/stereo/left/image_raw` or `/stereo/right/image_raw` (or the rectified image topics). The ROS package takes the raw image and split the channels into two separate topics.
